### ISSUE TITLE
Everything works in homebridge, but Tesvor X500 is not exposed to HomeKit

### ISSUE THREAD

**Issue by waywit** [marcelkordek/homebridge-tesvor#11]
**Describe The Bug:**
I have setup my Tester x500 with Weback App and installed your plugin to my home bridge. The configuration as "switch works" inside home bridge:
- I have a switch with the name ob my Tester x500
- I have the actual battery level
- I can start and stop the x500

BUT, I do not see the switch in my Apple Home App nor in my Eve App :-( I have updated everything and also made multiple restarts.

**To Reproduce:**
Fresh install and connect Tester x500 as Switch with Weback App

**Expected behavior:**
Tesvor x500 switch is shown in Home App.

**Logs:**
There is a Warning during startup, but I do not think that this can cause the issue, but maybe I am wrong ;-)

```
[25.11.2022, 12:25:19] [HomebridgeTesvor] Restoring existing accessory from cache: Heinz
[25.11.2022, 12:25:19] [homebridge-tesvor] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
```

Just remembered to start home bridge in DEBUG mode and check what the Tester Plugin is saying:

```
[25.11.2022, 12:39:05] Loaded plugin: homebridge-tesvor@1.0.10
[25.11.2022, 12:39:05] Registering platform 'homebridge-tesvor.HomebridgeTesvor'
[25.11.2022, 12:39:06] [HomebridgeTesvor] Initializing HomebridgeTesvor platform...
[25.11.2022, 12:39:06] [HomebridgeTesvor] Finished initializing platform: HomebridgeTesvor
[25.11.2022, 12:39:06] [HomebridgeTesvor] Loading accessory from cache: Heinz
[25.11.2022, 12:39:06] [HomebridgeTesvor] Executed didFinishLaunching callback
[25.11.2022, 12:39:06] [HomebridgeTesvor] deviceList() ...
[25.11.2022, 12:39:06] [HomebridgeTesvor] auth() ...
[25.11.2022, 12:39:08] [HomebridgeTesvor] getData() - checking token ...
[25.11.2022, 12:39:08] [HomebridgeTesvor] token expired: false
[25.11.2022, 12:39:08] [HomebridgeTesvor] Restoring existing accessory from cache: Heinz
[25.11.2022, 12:39:08] [homebridge-tesvor] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[25.11.2022, 12:39:08] [homebridge-tesvor] Error:
    at new SwitchAccessory (/var/lib/homebridge/node_modules/homebridge-tesvor/src/switchAccessory.ts:47:8)
    at /var/lib/homebridge/node_modules/homebridge-tesvor/src/platform.ts:109:15
[25.11.2022, 12:39:09] [HomebridgeTesvor] Get Characteristic On -> false
[25.11.2022, 12:39:09] [HomebridgeTesvor] sending ...
[25.11.2022, 12:39:09] [HomebridgeTesvor] Websocket readyState:  0
[25.11.2022, 12:39:09] [HomebridgeTesvor] Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/var/lib/homebridge/node_modules/homebridge-tesvor/node_modules/ws/lib/websocket.js:394:13)
    at WsMonitor.send (/var/lib/homebridge/node_modules/homebridge-tesvor/src/lib/WsMonitor.js:43:15)
    at WsMonitor.getUpdate (/var/lib/homebridge/node_modules/homebridge-tesvor/src/lib/WsMonitor.js:36:10)
    at SwitchAccessory.getOn (/var/lib/homebridge/node_modules/homebridge-tesvor/src/switchAccessory.ts:179:13)
[25.11.2022, 12:39:09] [HomebridgeTesvor] ty-x500-xx-yy-zz-xx-yy-zz - websocket listening on wss://user.grit-cloud.com/prod/wss
[25.11.2022, 12:39:09] [HomebridgeTesvor] sending ...
[25.11.2022, 12:39:09] [HomebridgeTesvor] Websocket readyState:  1
[25.11.2022, 12:39:09] [HomebridgeTesvor] pong
[25.11.2022, 12:39:10] [HomebridgeTesvor] ty-x500-xx-yy-zz-xx-yy-zz - notification received
[25.11.2022, 12:39:39] [HomebridgeTesvor] sending ...
[25.11.2022, 12:39:39] [HomebridgeTesvor] Websocket readyState:  1
[25.11.2022, 12:39:40] [HomebridgeTesvor] ty-x500-xx-yy-zz-xx-yy-zz - notification received
[25.11.2022, 12:40:09] [HomebridgeTesvor] sending ...
[25.11.2022, 12:40:09] [HomebridgeTesvor] Websocket readyState:  1
[25.11.2022, 12:40:10] [HomebridgeTesvor] ty-x500-xx-yy-zz-xx-yy-zz - notification received
```

**Plugin Config:**

<img width="803" alt="tesvor-x500" src="https://user-images.githubusercontent.com/8435459/203979744-c62ccb79-ae48-492c-975c-69fedc421211.png">

```json
        {
            "username": "xyz@xyz.xyz",
            "password": "XXX",
            "country": "0049",
            "accessoryType": "Switch",
            "startMode": "AutoClean",
            "stopMode": "BackCharging",
            "fanMode": "Normal",
            "appName": "WeBack",
            "platform": "HomebridgeTesvor"
        }
```

**Environment:**

* **Plugin Version**: 1.0.10
* **Homebridge Version**: 1.5.1
* **Node.js Version**: 18.12.1
* **NPM Version**: 8.19.2
* **Operating System**: hb-shell with Debian Buster

**Comment by marcelkordek** [comment]
Hi,

I just uploaded an update. Please test version 1.0.12.
Hopefully that fixes the bug.

Regards
Marcel

**Comment by waywit** [comment]
Yeah... Thanks, now Heinz is shown in Home-App and also in Eve-App 😊 By the way, I checked 1.6.0 Homebridge too and it works there 👍🏻
